version: 2
executorType: docker
containerInfo:
    - image: ubuntu:14.04
      env:
        - DISPLAY=:99
        - CHROME_BIN=/usr/bin/google-chrome

- type: shell
  name: Starting Xvfb (for Browser Tests)
  command: Xvfb :99 -screen 0 1280x1024x24
   background: true
   
    - image: circleci/openjdk:8-jdk
    - image: selenium/standalone-chrome:3.1.0
   
    steps:
    - checkout
    - run: sudo apt update
    - run: xvfb-run java -Dwebdriver.chrome.driver=../chromedriver -jar ../seleniumserverstandalone.jar >/dev/null 2>&1 &
    - run: javac src/Test.java
    - run: java src/Test
workflows:
  version: 2
  workflow:
    jobs:
    - build
