version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - run: sudo apt update
    - run: google-chrome --version
    - run: xvfb-run java -Dwebdriver.chrome.driver=../chromedriver -jar ../selenium-server-standalone.jar >/dev/null 2>&1 &
    - run: chromedriver --version
    - run: java -version
    - run: echo Main-Class: Test >manifest.txt
    - run: jar cvfm Test.jar manifest.txt src/Test.java
    - run: jar cvf Test.jar src/Test.java
    - run: java -jar Test.jar
workflows:
  version: 2
  workflow:
    jobs:
    - build
