version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    - image: selenium/standalone-chrome:3.1.0
    steps:
    - checkout
    - run: sudo apt update
    - run: xvfb-run java -Dwebdriver.chrome.driver=../chromedriver -jar ../seleniumserverstandalone.jar >/dev/null 2>&1 &
    - run: javac src/Test.java
    - run: java src/Test
workflows:
  version: 2
  workflow:
    jobs:
    - build
